version: 0.1

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --no-progress --silent
  build:
    commands:
      - mkdir -p target/dev
      - export SERVERLESS_ACCESS_KEY=AKiTHgfMcZdsxyXA8W2e67xLMFhDM9PvpIAuwHrVvMXMO
      - serverless package --package target/dev --stage dev
      
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
