version: 0.1

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  build:
    commands:
      - bash deploy.sh
