version: 0.1

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --no-progress --silent
  build:
    commands:
      - mkdir -p target/dev
      - echo SLS Access Key `$SERVERLESS_ACCESS_KEY`
      - echo SLS Debug Level `$SLS_DEBUG`
      - serverless package --package target/dev --stage dev
      
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
