service: mobilus
app: mobilus
org: chrisrothwell
frameworkVersion: '2'

custom:
  DYTBL: 'mob-${self:provider.stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      shell: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: '*'
  environment:
    DYTBL: ${self:custom.DYTBL}

functions:
  app:
    handler: index.handler
    events:
      - http:
         path: /{proxy+}
         method: ANY
         cors: true
    timeout: 30
  cron:
    handler: cron.dailySchedule
    events:
      - schedule: cron(0 1 * * ? *)
      - schedule: cron(5 1 * * ? *)
      - schedule: cron(10 1 * * ? *)
    timeout: 300
resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: nid
            AttributeType: S
        KeySchema:
          -
            AttributeName: nid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.DYTBL}

plugins:
#  - serverless-dynamodb-local
#  - serverless-offline
#  - serverless-plugin-chrome
